server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trendify_db?CreateDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


